### PR TITLE
imagehoster major refactoring

### PR DESCRIPTION
**Pull request by jnordberg**
## Todo

 - [x] Upload rate limiting #57 
 - [x] User avatar endpoint #53 
 - [x] Caching headers #56 #55 
 - [x] Upload and url blacklists #58
 - [x] Copy proxied images to s3 #62

### CODE REVIEW

**Comment by jnordberg** [comment]
Ready to go!

**Comment by jnordberg** [comment]
Functionality differences from previous version:

Service is now designed to sit behind a caching proxy (aws cloudfront in our case). Fetched images are no longer copied to s3 and their cache headers are respected (to a point, minimum 1 hour). This should speed up the website considerably for users outside the US and probably reduce our operating costs a bit as well.

Other then that it is same same, but different, but still same.

**Comment by sneak** [comment]
I need to review this to make sure it meets our requirements; the part about not saving copies to S3 concerns me. I will review today.

**Comment by sneak** [comment]
There is no reason or need to support both node8 and node9 in testing. Because this is dockerized in prod, it will never run on 8.

**Comment by jnordberg** [comment]
I disagree, if node 9 introduces a bug that causes the 9 tests to fail while 8 is still passing we get some really valuable information on what the cause might be. There is no cost of having those tests, they don't slow down the build, they don't require any maintenance and if they start failing we can remove them knowing that the app no longer supports node 8

**Comment by sneak** [comment]
I’m fine with that. My argument against it is the same as that against needing commented out code in `master`. If you think it provides debugging value, keep it. Note that we will never run it under node8, nor should anyone else.

**Comment by sneak** [comment]
*keeping commented

**Comment by sneak** [comment]
caching images for all time is a design goal.

**Comment by jnordberg** [comment]
Ok, added it to todo

**Pull request merged**
