### PR TITLE
Community - Automatically rotate images

### PR DESCRIPTION
**Pull request by roadscape**
From @quochuy #116:

> Automatically rotate images that were taken in portrait mode from a mobile phone
> 
> Photos taken from a mobile phone in portrait mode have an EXIF metadata that tells the viewing software (in this case the browser) to rotate the image. However, the image proxy does not perform the rotation.
> 
> **Example of the issue**
> Example image from https://steemit.com/wales/@trystan/rest-in-peace-dad-rip-wales
> 
> Original image (notice that the image is correctly oriented): 
> https://cdn.steemitimages.com/DQmTssGEdhm4RiuHTwqn7KoT78ZdadWKLFjSTeXvU5gSTyi/90FD4E69-3CE8-478A-A8C2-6044EAF86FAD.jpeg
> 
> Proxied image (noticed it is now rotated 90 degrees to the left):
> https://steemitimages.com/640x0/https://cdn.steemitimages.com/DQmTssGEdhm4RiuHTwqn7KoT78ZdadWKLFjSTeXvU5gSTyi/90FD4E69-3CE8-478A-A8C2-6044EAF86FAD.jpeg
> 
> After the fix, it's now resized to 640x0 and correctly oriented:
> Screen Shot 2019-12-16 at 8 32 31 pm
> 
> **Counter test**
> I've tested against an original landscape image and it does not perform a extra rotation, the image is correctly oriented.
> 
> **Got the hint from:**
> https://github.com/lovell/sharp/issues/903
>

### CODE REVIEW

**Comment by roadscape** [comment]
@quochuy tests reveal an error:

```
TSError: ⨯ Unable to compile TypeScript:
src/proxy.ts(322,55): error TS2345: Argument of type '{ fit: string; }' is not assignable to parameter of type 'ResizeOptions | undefined'.
  Object literal may only specify known properties, and 'fit' does not exist in type 'ResizeOptions | undefined'.
```

**Comment by quochuy** [comment]
Ok, I added this because crop() is deprecated. Will check and see what I can do or else revert the line to how it was as it was only outputting a warning, not an error

**Comment by quochuy** [comment]
Looks like package.json is using sharp v0.21.0 but is using @types/sharp v0.17.6.
Trying to fix this

**Comment by quochuy** [comment]
https://github.com/steemit/imagehoster/pull/119

**Pull request merged**
